version: '3'
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
    ports:
      - "5432:5432"
    volumes:
    - ./server/sql/schemas.sql:/docker-entrypoint-initdb.d/schemas.sql
    - ./server/sql/seeds.sql:/docker-entrypoint-initdb.d/seeds.sql
  # server:
  #   build:
  #     context: ./server
  #     dockerfile: Dockerfile
  #   ports:
  #     - '3001:3001'
  #   environment:
  #     - NODE_ENV=production
  #     - PORT=3001
  #     - DATABASE_URL=postgresql://postgres:123456@postgres:5432/postgres
  #     - DATABASE_SSL=false
  #     - ACCESS_CONTROL_ALLOW_ORIGIN=*
  #   depends_on:
  #       - postgres
  # site:
  #   build:
  #     context: ./site
  #     dockerfile: Dockerfile
  #   ports:
  #     - '3000:3000'
  #   environment:
  #     - NODE_ENV=production